apiVersion: v1
kind: Pod
metadata:
  name: hive-metastore-postgres
  labels:
    app: hive-pod
spec:
  nodeSelector:
    pod: "hive"
    role: "metastore"
  serviceAccountName: trino

  volumes:
    - name: hive-site-config
      configMap:
        name: hive-site-config
    - name: core-site-config
      configMap:
        name: core-site-config
    - name: hms-warehouse
      emptyDir: {}
    - name: auxlib
      emptyDir: {}   # will hold the Postgres JDBC jar

  initContainers:
    - name: fetch-pg-jdbc
      image: curlimages/curl:8.10.1
      command: [ "sh","-lc" ]
      args:
        - |
          set -euo pipefail
          mkdir -p /aux
          URL1="https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.4/postgresql-42.7.4.jar"
          URL2="https://jdbc.postgresql.org/download/postgresql-42.7.4.jar"
          echo "Downloading JDBC (Maven Central)…"
          if ! curl -fL --retry 5 --retry-connrefused --connect-timeout 10 -o /aux/postgresql-42.7.4.jar "$URL1"; then
            echo "Primary failed; trying vendor URL…"
            curl -fL --retry 5 --retry-connrefused --connect-timeout 10 -o /aux/postgresql-42.7.4.jar "$URL2"
          fi
          test -s /aux/postgresql-42.7.4.jar
      volumeMounts:
        - name: auxlib
          mountPath: /aux

  containers:
    - name: hive-metastore
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        capabilities:
          drop:
            - MKNOD
      image: apache/hive:standalone-metastore-4.1.0 # Requires a different HMS version for ABFS compatability
      imagePullPolicy: IfNotPresent
      env:
        - name: METASTORE_PREPEND_CLASSPATH
          value: "true"
        - name: HIVE_AUX_JARS_PATH
          value: /opt/hive/auxlib/postgresql-42.7.4.jar
        - name: HADOOP_CONF_DIR
          value: "/etc/hadoop/conf/"
        - name: HADOOP_OPTIONAL_TOOLS
          value: hadoop-azure
        - name: METASTORE_LISTEN_HOST
          value: "0.0.0.0"
        - name: METASTORE_PORT
          value: "9083"

      ports:
        - containerPort: 9083

      volumeMounts:
        - name: hive-site-config
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml
        - name: core-site-config
          mountPath: /etc/hadoop/conf/core-site.xml
          subPath: core-site.xml
        - name: hms-warehouse
          mountPath: /tmp/hive/warehouse
        - name: auxlib
          mountPath: /opt/hive/auxlib

      command: ["/bin/bash","-lc"]
      args:
        - |
          set -e
          
          mkdir -p /opt/hive/lib
          cp -f /opt/hive/auxlib/postgresql-42.7.4.jar /opt/hive/lib/

          echo "Waiting for Postgres (TCP 5432)..."
          # portable TCP wait (no netcat needed)
          for i in {1..5}; do
            (exec 3<>/dev/tcp/localhost/5432) >/dev/null 2>&1 && break || true
            sleep 2
          done

          if /opt/hive/bin/schematool -dbType postgres -info >/dev/null 2>&1; then
            echo "Schema present; skipping init."
          else
            echo "Initializing Hive metastore schema..."
            /opt/hive/bin/schematool -initSchema -dbType postgres -verbose
          fi

          exec /opt/hive/bin/start-metastore

    - name: postgres
      image: postgres:13
      env:
        - name: POSTGRES_DB
          value: metastore
        - name: POSTGRES_USER
          value: hive
        - name: POSTGRES_PASSWORD
          value: hivepass
      ports:
        - containerPort: 5432
      resources:
        requests: { cpu: "500m", memory: "0.5Gi" }
        limits:   { cpu: "500m", memory: "0.5Gi" }
